# Generated by Django 2.1.7 on 2024-07-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestFileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uploaderemail', models.EmailField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('filename', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='static\\Reqfiles')),
                ('encrypted_data', models.BinaryField()),
                ('encrypted_key', models.CharField(max_length=1000)),
                ('tag', models.CharField(max_length=1000)),
                ('nonce', models.CharField(max_length=1000)),
                ('status', models.CharField(default='pending', max_length=100, null=True)),
            ],
            options={
                'db_table': 'RequestFileModel',
            },
        ),
        migrations.CreateModel(
            name='UplaodFileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uploaderemail', models.EmailField(max_length=254)),
                ('filename', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='static\\files')),
                ('encrypted_data', models.BinaryField()),
                ('encrypted_key', models.BinaryField()),
                ('tag', models.BinaryField()),
                ('nonce', models.BinaryField()),
                ('decrypted_data', models.BinaryField()),
            ],
            options={
                'db_table': 'UplaodFileModel',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('profile', models.FileField(upload_to='static\\UserModel')),
            ],
            options={
                'db_table': 'UserModel',
            },
        ),
    ]
