# Generated by Django 2.1.7 on 2024-07-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestfilemodel',
            name='decrypted_data',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='uplaodfilemodel',
            name='decrypted_data',
            field=models.TextField(),
        ),
    ]
