# Generated by Django 5.1.7 on 2025-03-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20240729_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.FileField(upload_to='static/uploads')),
                ('image2', models.FileField(upload_to='static/uploads')),
                ('output', models.CharField(max_length=100, null=True)),
                ('uploader', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='RequestFileModel',
        ),
        migrations.DeleteModel(
            name='UplaodFileModel',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
