# Generated by Django 5.1.7 on 2025-03-19 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_images_delete_requestfilemodel_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='images',
            table='Images',
        ),
    ]
