# Generated by Django 6.0.6 on 2026-06-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.FileField(upload_to='uploads/')),
                ('image2', models.FileField(upload_to='uploads/')),
                ('output', models.CharField(max_length=100, null=True)),
                ('uploader', models.EmailField(max_length=254, null=True)),
            ],
            options={
                'db_table': 'Images',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('profile', models.FileField(upload_to='profiles/')),
            ],
            options={
                'db_table': 'UserModel',
            },
        ),
    ]
